2018-04-10T10:37:35.6235113+07:00 0HLCUIHJ8D8LK:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/values   (ca22a1cb)
2018-04-10T10:37:35.7396739+07:00 0HLCUIHJ8D8LK:00000001 [INF] Request finished in 134.9036ms 404  (791a596a)
2018-04-10T10:37:42.5469195+07:00 0HLCUIHJ8D8LK:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger   (ca22a1cb)
2018-04-10T10:37:42.5496509+07:00 0HLCUIHJ8D8LK:00000002 [INF] Request finished in 2.6681ms 301  (791a596a)
2018-04-10T10:37:42.5571024+07:00 0HLCUIHJ8D8LK:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/   (ca22a1cb)
2018-04-10T10:37:42.5737046+07:00 0HLCUIHJ8D8LK:00000003 [INF] Request finished in 16.7102ms 200 text/html (791a596a)
2018-04-10T10:37:42.6196597+07:00 0HLCUIHJ8D8LK:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/swagger-ui-standalone-preset.js   (ca22a1cb)
2018-04-10T10:37:42.6241222+07:00 0HLCUIHJ8D8LK:00000004 [INF] Sending file. Request path: '"/swagger-ui-standalone-preset.js"'. Physical path: '"N/A"' (27b0a520)
2018-04-10T10:37:42.6287784+07:00 0HLCUIHJ8D8LL:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/swagger-ui-bundle.js   (ca22a1cb)
2018-04-10T10:37:42.6296428+07:00 0HLCUIHJ8D8LL:00000001 [INF] Sending file. Request path: '"/swagger-ui-bundle.js"'. Physical path: '"N/A"' (27b0a520)
2018-04-10T10:37:42.6321672+07:00 0HLCUIHJ8D8LM:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/swagger-ui.css   (ca22a1cb)
2018-04-10T10:37:42.6326193+07:00 0HLCUIHJ8D8LM:00000001 [INF] Sending file. Request path: '"/swagger-ui.css"'. Physical path: '"N/A"' (27b0a520)
2018-04-10T10:37:42.6517174+07:00 0HLCUIHJ8D8LM:00000001 [INF] Request finished in 19.5693ms 200 text/css (791a596a)
2018-04-10T10:37:42.6664954+07:00 0HLCUIHJ8D8LK:00000004 [INF] Request finished in 46.8909ms 200 application/javascript (791a596a)
2018-04-10T10:37:42.7131761+07:00 0HLCUIHJ8D8LL:00000001 [INF] Request finished in 84.3744ms 200 application/javascript (791a596a)
2018-04-10T10:37:43.4703147+07:00 0HLCUIHJ8D8LM:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/v1/swagger.json   (ca22a1cb)
2018-04-10T10:37:43.5998887+07:00 0HLCUIHJ8D8LK:00000005 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/favicon-32x32.png   (ca22a1cb)
2018-04-10T10:37:43.6004863+07:00 0HLCUIHJ8D8LK:00000005 [INF] Sending file. Request path: '"/favicon-32x32.png"'. Physical path: '"N/A"' (27b0a520)
2018-04-10T10:37:43.6013448+07:00 0HLCUIHJ8D8LK:00000005 [INF] Request finished in 1.2646ms 200 image/png (791a596a)
2018-04-10T10:37:43.6270237+07:00 0HLCUIHJ8D8LL:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/favicon-16x16.png   (ca22a1cb)
2018-04-10T10:37:43.6275495+07:00 0HLCUIHJ8D8LL:00000002 [INF] Sending file. Request path: '"/favicon-16x16.png"'. Physical path: '"N/A"' (27b0a520)
2018-04-10T10:37:43.6279466+07:00 0HLCUIHJ8D8LL:00000002 [INF] Request finished in 1ms 200 image/png (791a596a)
2018-04-10T10:37:43.7788956+07:00 0HLCUIHJ8D8LM:00000002 [INF] Request finished in 308.5979ms 200 application/json (791a596a)
2018-04-10T10:37:53.2386490+07:00 0HLCUIHJ8D8LK:00000006 [INF] Request starting HTTP/1.1 DELETE http://localhost:52568/api/CategoryBooking?id=1   (ca22a1cb)
2018-04-10T10:37:53.3349883+07:00 0HLCUIHJ8D8LK:00000006 [INF] Executed action "OneTravelApi.Controllers.CategoryBookingController.Delete (OneTravelApi)" in 7.4831ms (afa2e885)
2018-04-10T10:37:53.4103772+07:00 0HLCUIHJ8D8LK:00000006 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Unable to resolve service for type 'OneTravelApi.Services.ICategoryBookingService' while attempting to activate 'OneTravelApi.Controllers.CategoryBookingController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-10T10:37:53.5253077+07:00 0HLCUIHJ8D8LK:00000006 [INF] Request finished in 286.6915ms 500 text/html; charset=utf-8 (791a596a)
2018-04-10T10:38:44.8808661+07:00 0HLCUII7STULG:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/values   (ca22a1cb)
2018-04-10T10:38:44.9913349+07:00 0HLCUII7STULG:00000001 [INF] Request finished in 131.9691ms 404  (791a596a)
2018-04-10T10:38:45.4971632+07:00 0HLCUII7STULG:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/   (ca22a1cb)
2018-04-10T10:38:45.5120710+07:00 0HLCUII7STULG:00000002 [INF] Request finished in 15.0274ms 200 text/html (791a596a)
2018-04-10T10:38:46.4837436+07:00 0HLCUII7STULG:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/v1/swagger.json   (ca22a1cb)
2018-04-10T10:38:46.5278718+07:00 0HLCUII7STULH:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/favicon-32x32.png   (ca22a1cb)
2018-04-10T10:38:46.5326440+07:00 0HLCUII7STULH:00000001 [INF] Sending file. Request path: '"/favicon-32x32.png"'. Physical path: '"N/A"' (27b0a520)
2018-04-10T10:38:46.5382742+07:00 0HLCUII7STULH:00000001 [INF] Request finished in 10.4216ms 200 image/png (791a596a)
2018-04-10T10:38:46.7917931+07:00 0HLCUII7STULG:00000003 [INF] Request finished in 307.9919ms 200 application/json (791a596a)
2018-04-10T10:38:55.2826938+07:00 0HLCUII7STULH:00000002 [INF] Request starting HTTP/1.1 DELETE http://localhost:52568/api/CategoryBooking?id=1   (ca22a1cb)
2018-04-10T10:38:55.3974195+07:00 0HLCUII7STULH:00000002 [INF] Executing action method "OneTravelApi.Controllers.CategoryBookingController.Delete (OneTravelApi)" with arguments (["1"]) - ModelState is Valid (ba7f4ac2)
2018-04-10T10:38:55.8537766+07:00 0HLCUII7STULH:00000002 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2018-04-10T10:38:55.8646132+07:00 0HLCUII7STULH:00000002 [INF] Executed action "OneTravelApi.Controllers.CategoryBookingController.Delete (OneTravelApi)" in 520.1461ms (afa2e885)
2018-04-10T10:38:55.8652581+07:00 0HLCUII7STULH:00000002 [INF] Request finished in 582.6535ms 200 application/json; charset=utf-8 (791a596a)
2018-04-10T10:40:00.6094201+07:00 0HLCUII7STULI:00000001 [INF] Request starting HTTP/1.1 DELETE http://localhost:52568/api/CategoryBooking?id=-9999   (ca22a1cb)
2018-04-10T10:40:00.6113087+07:00 0HLCUII7STULI:00000001 [INF] Executing action method "OneTravelApi.Controllers.CategoryBookingController.Delete (OneTravelApi)" with arguments (["-9999"]) - ModelState is Valid (ba7f4ac2)
2018-04-10T10:40:00.6353495+07:00 0HLCUII7STULI:00000001 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2018-04-10T10:40:00.6359898+07:00 0HLCUII7STULI:00000001 [INF] Executed action "OneTravelApi.Controllers.CategoryBookingController.Delete (OneTravelApi)" in 25.7699ms (afa2e885)
2018-04-10T10:40:00.6364209+07:00 0HLCUII7STULI:00000001 [INF] Request finished in 27.0533ms 200 application/json; charset=utf-8 (791a596a)
2018-04-10T10:40:33.8843602+07:00 0HLCUII7STULI:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:52568/api/CategoryBooking application/json-patch+json 77 (ca22a1cb)
2018-04-10T10:40:33.9335631+07:00 0HLCUII7STULI:00000002 [INF] Executing action method "OneTravelApi.Controllers.CategoryBookingController.Create (OneTravelApi)" with arguments (["OneTravelApi.EntityLayer.CategoryBooking"]) - ModelState is Valid (ba7f4ac2)
2018-04-10T10:40:34.0401447+07:00 0HLCUII7STULI:00000002 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2018-04-10T10:40:34.0404897+07:00 0HLCUII7STULI:00000002 [INF] Executed action "OneTravelApi.Controllers.CategoryBookingController.Create (OneTravelApi)" in 148.0929ms (afa2e885)
2018-04-10T10:40:34.0453439+07:00 0HLCUII7STULI:00000002 [INF] Request finished in 160.9534ms 200 application/json; charset=utf-8 (791a596a)
2018-04-10T11:00:37.6223988+07:00 0HLCUIUF4BKQ4:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/values   (ca22a1cb)
2018-04-10T11:00:37.7142824+07:00 0HLCUIUF4BKQ4:00000001 [INF] Request finished in 110.8905ms 404  (791a596a)
2018-04-10T11:00:41.4847195+07:00 0HLCUIUF4BKQ4:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/   (ca22a1cb)
2018-04-10T11:00:41.4990963+07:00 0HLCUIUF4BKQ4:00000002 [INF] Request finished in 14.9698ms 200 text/html (791a596a)
2018-04-10T11:00:42.3432476+07:00 0HLCUIUF4BKQ4:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/v1/swagger.json   (ca22a1cb)
2018-04-10T11:00:42.3797676+07:00 0HLCUIUF4BKQ5:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/favicon-32x32.png   (ca22a1cb)
2018-04-10T11:00:42.3841052+07:00 0HLCUIUF4BKQ5:00000001 [INF] Sending file. Request path: '"/favicon-32x32.png"'. Physical path: '"N/A"' (27b0a520)
2018-04-10T11:00:42.3892035+07:00 0HLCUIUF4BKQ5:00000001 [INF] Request finished in 9.4685ms 200 image/png (791a596a)
2018-04-10T11:00:42.6124114+07:00 0HLCUIUF4BKQ4:00000003 [INF] Request finished in 268.0517ms 200 application/json (791a596a)
2018-04-10T11:00:49.7239816+07:00 0HLCUIUF4BKQ5:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/CategoryBooking   (ca22a1cb)
2018-04-10T11:00:49.8305037+07:00 0HLCUIUF4BKQ5:00000002 [INF] Executing action method "OneTravelApi.Controllers.CategoryBookingController.GetAll (OneTravelApi)" with arguments (["10", "1", ""]) - ModelState is Valid (ba7f4ac2)
2018-04-10T11:00:50.3700670+07:00 0HLCUIUF4BKQ5:00000002 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2018-04-10T11:00:50.3884262+07:00 0HLCUIUF4BKQ5:00000002 [INF] Executed action "OneTravelApi.Controllers.CategoryBookingController.GetAll (OneTravelApi)" in 605.3546ms (afa2e885)
2018-04-10T11:00:50.3890942+07:00 0HLCUIUF4BKQ5:00000002 [INF] Request finished in 665.1082ms 200 application/json; charset=utf-8 (791a596a)
2018-04-10T11:01:25.1332362+07:00 0HLCUIUT9BCD5:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/values   (ca22a1cb)
2018-04-10T11:01:25.2403020+07:00 0HLCUIUT9BCD6:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/CategoryBooking   (ca22a1cb)
2018-04-10T11:01:25.2439617+07:00 0HLCUIUT9BCD5:00000001 [INF] Request finished in 130.6852ms 404  (791a596a)
2018-04-10T11:01:25.4509060+07:00 0HLCUIUT9BCD6:00000001 [INF] Executing action method "OneTravelApi.Controllers.CategoryBookingController.GetAll (OneTravelApi)" with arguments (["10", "1", ""]) - ModelState is Valid (ba7f4ac2)
2018-04-10T11:01:25.4635517+07:00 0HLCUIUT9BCD6:00000001 [INF] Executed action "OneTravelApi.Controllers.CategoryBookingController.GetAll (OneTravelApi)" in 108.0287ms (afa2e885)
2018-04-10T11:01:25.5741870+07:00 0HLCUIUT9BCD6:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.Exception: Lỗi rồi bạn ơi
   at OneTravelApi.Controllers.CategoryBookingController.GetAll(Nullable`1 pageSize, Nullable`1 pageNumber, String q) in D:\dev\projects\OneTravelCMS\OneTravelApi\Controllers\CategoryBookingController.cs:line 21
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-10T11:01:25.6555886+07:00 0HLCUIUT9BCD6:00000001 [INF] Request finished in 415.6806ms 500 text/html; charset=utf-8 (791a596a)
2018-04-10T11:01:54.5090740+07:00 0HLCUIV61E9R0:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/values   (ca22a1cb)
2018-04-10T11:01:54.6601091+07:00 0HLCUIV61E9R0:00000001 [INF] Request finished in 172.978ms 404  (791a596a)
2018-04-10T11:01:57.8395265+07:00 0HLCUIV61E9R0:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/CategoryBooking   (ca22a1cb)
2018-04-10T11:01:58.0099221+07:00 0HLCUIV61E9R0:00000002 [INF] Executing action method "OneTravelApi.Controllers.CategoryBookingController.GetAll (OneTravelApi)" with arguments (["10", "1", ""]) - ModelState is Valid (ba7f4ac2)
2018-04-10T11:01:58.0178502+07:00 0HLCUIV61E9R0:00000002 [INF] Executed action "OneTravelApi.Controllers.CategoryBookingController.GetAll (OneTravelApi)" in 82.796ms (afa2e885)
2018-04-10T11:01:58.1058946+07:00 0HLCUIV61E9R0:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.Exception: Lỗi rồi bạn ơi
   at OneTravelApi.Services.CategoryBookingService.GetAll(Nullable`1 pageSize, Nullable`1 pageNumber, String q) in D:\dev\projects\OneTravelCMS\OneTravelApi\Services\ICategoryBookingService.cs:line 37
   at OneTravelApi.Controllers.CategoryBookingController.GetAll(Nullable`1 pageSize, Nullable`1 pageNumber, String q) in D:\dev\projects\OneTravelCMS\OneTravelApi\Controllers\CategoryBookingController.cs:line 21
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-10T11:01:58.1729850+07:00 0HLCUIV61E9R0:00000002 [INF] Request finished in 333.5927ms 500 text/html; charset=utf-8 (791a596a)
2018-04-10T11:02:41.2381069+07:00 0HLCUIVJV6ANT:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/values   (ca22a1cb)
2018-04-10T11:02:41.3456229+07:00 0HLCUIVJV6ANT:00000001 [INF] Request finished in 126.2062ms 404  (791a596a)
2018-04-10T11:02:47.2525190+07:00 0HLCUIVJV6ANT:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/CategoryBooking   (ca22a1cb)
2018-04-10T11:02:47.4334103+07:00 0HLCUIVJV6ANT:00000002 [INF] Executing action method "OneTravelApi.Controllers.CategoryBookingController.GetAll (OneTravelApi)" with arguments (["10", "1", ""]) - ModelState is Valid (ba7f4ac2)
2018-04-10T11:02:47.9492367+07:00 0HLCUIVJV6ANT:00000002 [INF] Executed action "OneTravelApi.Controllers.CategoryBookingController.GetAll (OneTravelApi)" in 591.2228ms (afa2e885)
2018-04-10T11:02:48.0176846+07:00 0HLCUIVJV6ANT:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.NullReferenceException: Object reference not set to an instance of an object.
   at OneTravelApi.Services.CategoryBookingService.GetAll(Nullable`1 pageSize, Nullable`1 pageNumber, String q) in D:\dev\projects\OneTravelCMS\OneTravelApi\Services\ICategoryBookingService.cs:line 63
   at OneTravelApi.Controllers.CategoryBookingController.GetAll(Nullable`1 pageSize, Nullable`1 pageNumber, String q) in D:\dev\projects\OneTravelCMS\OneTravelApi\Controllers\CategoryBookingController.cs:line 21
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-10T11:02:48.0913299+07:00 0HLCUIVJV6ANT:00000002 [INF] Request finished in 838.9667ms 500 text/html; charset=utf-8 (791a596a)
2018-04-10T11:03:23.1476871+07:00 0HLCUIVJV6ANT:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/CategoryBooking   (ca22a1cb)
2018-04-10T11:03:23.1495047+07:00 0HLCUIVJV6ANT:00000003 [INF] Executing action method "OneTravelApi.Controllers.CategoryBookingController.GetAll (OneTravelApi)" with arguments (["10", "1", ""]) - ModelState is Valid (ba7f4ac2)
2018-04-10T11:03:23.1653790+07:00 0HLCUIVJV6ANT:00000003 [INF] Executed action "OneTravelApi.Controllers.CategoryBookingController.GetAll (OneTravelApi)" in 16.6932ms (afa2e885)
2018-04-10T11:03:23.2137975+07:00 0HLCUIVJV6ANT:00000003 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.NullReferenceException: Object reference not set to an instance of an object.
   at OneTravelApi.Services.CategoryBookingService.GetAll(Nullable`1 pageSize, Nullable`1 pageNumber, String q) in D:\dev\projects\OneTravelCMS\OneTravelApi\Services\ICategoryBookingService.cs:line 63
   at OneTravelApi.Controllers.CategoryBookingController.GetAll(Nullable`1 pageSize, Nullable`1 pageNumber, String q) in D:\dev\projects\OneTravelCMS\OneTravelApi\Controllers\CategoryBookingController.cs:line 21
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-10T11:03:23.2801658+07:00 0HLCUIVJV6ANT:00000003 [INF] Request finished in 132.5889ms 500 text/html; charset=utf-8 (791a596a)
2018-04-10T11:04:51.0615366+07:00 0HLCUJ0QL8FDS:00000001 [INF] Request starting HTTP/1.1 PUT http://localhost:52568/api/CategoryBooking/1 application/json-patch+json 64 (ca22a1cb)
2018-04-10T11:04:51.2992304+07:00 0HLCUJ0QL8FDS:00000001 [INF] Executing action method "OneTravelApi.Controllers.CategoryBookingController.Update (OneTravelApi)" with arguments (["1", "OneTravelApi.EntityLayer.CategoryBooking"]) - ModelState is Valid (ba7f4ac2)
2018-04-10T11:04:51.8613427+07:00 0HLCUJ0QL8FDS:00000001 [INF] Executed action "OneTravelApi.Controllers.CategoryBookingController.Update (OneTravelApi)" in 654.1224ms (afa2e885)
2018-04-10T11:04:51.9037479+07:00 0HLCUJ0QL8FDS:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.NullReferenceException: Object reference not set to an instance of an object.
   at OneTravelApi.Services.CategoryBookingService.<Update>d__7.MoveNext() in D:\dev\projects\OneTravelCMS\OneTravelApi\Services\ICategoryBookingService.cs:line 160
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OneTravelApi.Controllers.CategoryBookingController.<Update>d__3.MoveNext() in D:\dev\projects\OneTravelCMS\OneTravelApi\Controllers\CategoryBookingController.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-10T11:04:51.9761835+07:00 0HLCUJ0QL8FDS:00000001 [INF] Request finished in 933.2287ms 500 text/html; charset=utf-8 (791a596a)
2018-04-10T11:07:25.0962011+07:00 0HLCUJ28HFL7D:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/values   (ca22a1cb)
2018-04-10T11:07:25.2440107+07:00 0HLCUJ28HFL7D:00000001 [INF] Request finished in 172.6768ms 404  (791a596a)
2018-04-10T11:07:35.2945511+07:00 0HLCUJ28HFL7D:00000002 [INF] Request starting HTTP/1.1 PUT http://localhost:52568/api/CategoryBooking/1 application/json-patch+json 64 (ca22a1cb)
2018-04-10T11:07:35.5902979+07:00 0HLCUJ28HFL7D:00000002 [INF] Executing action method "OneTravelApi.Controllers.CategoryBookingController.Update (OneTravelApi)" with arguments (["1", "OneTravelApi.EntityLayer.CategoryBooking"]) - ModelState is Valid (ba7f4ac2)
2018-04-10T11:10:05.5485634+07:00 0HLCUJ3OBHN7D:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/values   (ca22a1cb)
2018-04-10T11:10:05.6975824+07:00 0HLCUJ3OBHN7D:00000001 [INF] Request finished in 181.8191ms 404  (791a596a)
2018-04-10T11:10:13.7183000+07:00 0HLCUJ3OBHN7D:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/   (ca22a1cb)
2018-04-10T11:10:13.7492588+07:00 0HLCUJ3OBHN7D:00000002 [INF] Request finished in 26.8213ms 200 text/html (791a596a)
2018-04-10T11:10:14.7746250+07:00 0HLCUJ3OBHN7D:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/v1/swagger.json   (ca22a1cb)
2018-04-10T11:10:14.8141813+07:00 0HLCUJ3OBHN7E:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/favicon-32x32.png   (ca22a1cb)
2018-04-10T11:10:14.8275509+07:00 0HLCUJ3OBHN7E:00000001 [INF] Sending file. Request path: '"/favicon-32x32.png"'. Physical path: '"N/A"' (27b0a520)
2018-04-10T11:10:14.8510847+07:00 0HLCUJ3OBHN7E:00000001 [INF] Request finished in 20.9446ms 200 image/png (791a596a)
2018-04-10T11:10:15.1072998+07:00 0HLCUJ3OBHN7D:00000003 [INF] Request finished in 326.4451ms 200 application/json (791a596a)
2018-04-10T11:10:32.4078246+07:00 0HLCUJ3OBHN7E:00000002 [INF] Request starting HTTP/1.1 PUT http://localhost:52568/api/CategoryBooking/1 application/json-patch+json 75 (ca22a1cb)
2018-04-10T11:10:32.6306973+07:00 0HLCUJ3OBHN7E:00000002 [INF] Executing action method "OneTravelApi.Controllers.CategoryBookingController.Update (OneTravelApi)" with arguments (["1", "OneTravelApi.EntityLayer.CategoryBooking"]) - ModelState is Valid (ba7f4ac2)
2018-04-10T11:11:15.3032757+07:00 0HLCUJ3OBHN7E:00000002 [INF] The property 'Id' on entity type 'CategoryBooking' is part of a key and so cannot be modified or marked as modified. To change the principal of an existing entity with an identifying foreign key first delete the dependent and invoke 'SaveChanges' then associate the dependent with the new principal. (fb2ae8ff)
2018-04-10T11:11:15.4350922+07:00 0HLCUJ3OBHN7E:00000002 [INF] Executed action "OneTravelApi.Controllers.CategoryBookingController.Update (OneTravelApi)" in 42928.2231ms (afa2e885)
2018-04-10T11:11:15.5188785+07:00 0HLCUJ3OBHN7E:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.NullReferenceException: Object reference not set to an instance of an object.
   at OneTravelApi.Services.CategoryBookingService.<Update>d__7.MoveNext() in D:\dev\projects\OneTravelCMS\OneTravelApi\Services\ICategoryBookingService.cs:line 161
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OneTravelApi.Controllers.CategoryBookingController.<Update>d__3.MoveNext() in D:\dev\projects\OneTravelCMS\OneTravelApi\Controllers\CategoryBookingController.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-10T11:11:15.6240200+07:00 0HLCUJ3OBHN7E:00000002 [INF] Request finished in 43215.2658ms 500 text/html; charset=utf-8 (791a596a)
2018-04-10T11:11:46.8522521+07:00 0HLCUJ3OBHN7E:00000003 [INF] Request starting HTTP/1.1 PUT http://localhost:52568/api/CategoryBooking/1 application/json-patch+json 75 (ca22a1cb)
2018-04-10T11:11:46.8717349+07:00 0HLCUJ3OBHN7E:00000003 [INF] Executing action method "OneTravelApi.Controllers.CategoryBookingController.Update (OneTravelApi)" with arguments (["1", "OneTravelApi.EntityLayer.CategoryBooking"]) - ModelState is Valid (ba7f4ac2)
2018-04-10T11:12:23.8474273+07:00 0HLCUJ3OBHN7E:00000003 [INF] The property 'Id' on entity type 'CategoryBooking' is part of a key and so cannot be modified or marked as modified. To change the principal of an existing entity with an identifying foreign key first delete the dependent and invoke 'SaveChanges' then associate the dependent with the new principal. (fb2ae8ff)
2018-04-10T11:12:23.9965289+07:00 0HLCUJ3OBHN7E:00000003 [INF] Executed action "OneTravelApi.Controllers.CategoryBookingController.Update (OneTravelApi)" in 37140.9654ms (afa2e885)
2018-04-10T11:12:24.0732198+07:00 0HLCUJ3OBHN7E:00000003 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.NullReferenceException: Object reference not set to an instance of an object.
   at OneTravelApi.Services.CategoryBookingService.<Update>d__7.MoveNext() in D:\dev\projects\OneTravelCMS\OneTravelApi\Services\ICategoryBookingService.cs:line 161
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OneTravelApi.Controllers.CategoryBookingController.<Update>d__3.MoveNext() in D:\dev\projects\OneTravelCMS\OneTravelApi\Controllers\CategoryBookingController.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-10T11:12:24.3179372+07:00 0HLCUJ3OBHN7E:00000003 [INF] Request finished in 37340.2271ms 500 text/html; charset=utf-8 (791a596a)
2018-04-10T11:14:10.5653374+07:00 0HLCUJ61D576K:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/values   (ca22a1cb)
2018-04-10T11:14:10.6619365+07:00 0HLCUJ61D576K:00000001 [INF] Request finished in 115.1571ms 404  (791a596a)
2018-04-10T11:14:13.5168490+07:00 0HLCUJ61D576K:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/   (ca22a1cb)
2018-04-10T11:14:13.5300352+07:00 0HLCUJ61D576K:00000002 [INF] Request finished in 13.1326ms 200 text/html (791a596a)
2018-04-10T11:14:14.1969610+07:00 0HLCUJ61D576K:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/v1/swagger.json   (ca22a1cb)
2018-04-10T11:14:14.2328081+07:00 0HLCUJ61D576L:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/favicon-32x32.png   (ca22a1cb)
2018-04-10T11:14:14.2380694+07:00 0HLCUJ61D576L:00000001 [INF] Sending file. Request path: '"/favicon-32x32.png"'. Physical path: '"N/A"' (27b0a520)
2018-04-10T11:14:14.2448569+07:00 0HLCUJ61D576L:00000001 [INF] Request finished in 12.0844ms 200 image/png (791a596a)
2018-04-10T11:14:14.4637740+07:00 0HLCUJ61D576K:00000003 [INF] Request finished in 266.7995ms 200 application/json (791a596a)
2018-04-10T11:15:08.7670249+07:00 0HLCUJ61D576L:00000002 [INF] Request starting HTTP/1.1 PUT http://localhost:52568/api/CategoryBooking/1 application/json-patch+json 75 (ca22a1cb)
2018-04-10T11:15:08.9089855+07:00 0HLCUJ61D576L:00000002 [INF] Executing action method "OneTravelApi.Controllers.CategoryBookingController.Update (OneTravelApi)" with arguments (["1", "OneTravelApi.EntityLayer.CategoryBooking"]) - ModelState is Valid (ba7f4ac2)
2018-04-10T11:15:09.4665344+07:00 0HLCUJ61D576L:00000002 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2018-04-10T11:15:09.4807403+07:00 0HLCUJ61D576L:00000002 [INF] Executed action "OneTravelApi.Controllers.CategoryBookingController.Update (OneTravelApi)" in 650.5466ms (afa2e885)
2018-04-10T11:15:09.4844210+07:00 0HLCUJ61D576L:00000002 [INF] Request finished in 717.3688ms 200 application/json; charset=utf-8 (791a596a)
2018-04-10T11:22:51.8592520+07:00 0HLCUJASOEFHT:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/values   (ca22a1cb)
2018-04-10T11:22:51.9849407+07:00 0HLCUJASOEFHT:00000001 [INF] Request finished in 147.7417ms 404  (791a596a)
2018-04-10T11:22:57.3720962+07:00 0HLCUJASOEFHT:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/   (ca22a1cb)
2018-04-10T11:22:57.3857781+07:00 0HLCUJASOEFHT:00000002 [INF] Request finished in 13.6761ms 200 text/html (791a596a)
2018-04-10T11:22:59.2084314+07:00 0HLCUJASOEFHT:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/v1/swagger.json   (ca22a1cb)
2018-04-10T11:22:59.2343214+07:00 0HLCUJASOEFHU:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/favicon-32x32.png   (ca22a1cb)
2018-04-10T11:22:59.2376562+07:00 0HLCUJASOEFHU:00000001 [INF] Sending file. Request path: '"/favicon-32x32.png"'. Physical path: '"N/A"' (27b0a520)
2018-04-10T11:22:59.2430598+07:00 0HLCUJASOEFHU:00000001 [INF] Request finished in 8.7094ms 200 image/png (791a596a)
2018-04-10T11:22:59.4776229+07:00 0HLCUJASOEFHT:00000003 [INF] Request finished in 269.2691ms 200 application/json (791a596a)
2018-04-10T11:23:12.0650789+07:00 0HLCUJASOEFHU:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/CategoryBookingStatus   (ca22a1cb)
2018-04-10T11:23:12.1797148+07:00 0HLCUJASOEFHU:00000002 [INF] Executing action method "OneTravelApi.Controllers.CategoryBookingStatusController.GetAll (OneTravelApi)" with arguments (["10", "1", ""]) - ModelState is Valid (ba7f4ac2)
2018-04-10T11:23:12.7133180+07:00 0HLCUJASOEFHU:00000002 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2018-04-10T11:23:12.7302938+07:00 0HLCUJASOEFHU:00000002 [INF] Executed action "OneTravelApi.Controllers.CategoryBookingStatusController.GetAll (OneTravelApi)" in 603.9645ms (afa2e885)
2018-04-10T11:23:12.7309890+07:00 0HLCUJASOEFHU:00000002 [INF] Request finished in 665.9498ms 200 application/json; charset=utf-8 (791a596a)
2018-04-10T11:23:24.2515148+07:00 0HLCUJASOEFHT:00000004 [INF] Request starting HTTP/1.1 POST http://localhost:52568/api/CategoryBookingStatus application/json-patch+json 116 (ca22a1cb)
2018-04-10T11:23:24.3178833+07:00 0HLCUJASOEFHT:00000004 [INF] Executing action method "OneTravelApi.Controllers.CategoryBookingStatusController.Create (OneTravelApi)" with arguments (["OneTravelApi.EntityLayer.CategoryBookingStatus"]) - ModelState is Valid (ba7f4ac2)
2018-04-10T11:23:24.4909800+07:00 0HLCUJASOEFHT:00000004 [ERR] System.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'BookingStatusCode', table 'OneTravelCMS.dbo.CategoryBookingStatuses'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__108_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()
ClientConnectionId:4516ecdc-664b-4fe0-8452-aef8fa497ab6
Error Number:515,State:2,Class:16 (ca58942b)
2018-04-10T11:23:24.4925084+07:00 0HLCUJASOEFHT:00000004 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2018-04-10T11:23:24.5010612+07:00 0HLCUJASOEFHT:00000004 [INF] Executed action "OneTravelApi.Controllers.CategoryBookingStatusController.Create (OneTravelApi)" in 239.5752ms (afa2e885)
2018-04-10T11:23:24.5046972+07:00 0HLCUJASOEFHT:00000004 [INF] Request finished in 253.1376ms 500 application/json; charset=utf-8 (791a596a)
2018-04-10T11:24:19.0532439+07:00 0HLCUJBMNRG9R:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:52568/api/CategoryBookingStatus application/json-patch+json 116 (ca22a1cb)
2018-04-10T11:24:19.3580657+07:00 0HLCUJBMNRG9R:00000001 [INF] Executing action method "OneTravelApi.Controllers.CategoryBookingStatusController.Create (OneTravelApi)" with arguments (["OneTravelApi.EntityLayer.CategoryBookingStatus"]) - ModelState is Valid (ba7f4ac2)
2018-04-10T11:24:19.9171720+07:00 0HLCUJBMNRG9R:00000001 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2018-04-10T11:24:19.9366793+07:00 0HLCUJBMNRG9R:00000001 [INF] Executed action "OneTravelApi.Controllers.CategoryBookingStatusController.Create (OneTravelApi)" in 706.7525ms (afa2e885)
2018-04-10T11:24:19.9410954+07:00 0HLCUJBMNRG9R:00000001 [INF] Request finished in 915.3952ms 200 application/json; charset=utf-8 (791a596a)
2018-04-10T11:24:26.7334496+07:00 0HLCUJBMNRG9R:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/CategoryBookingStatus   (ca22a1cb)
2018-04-10T11:24:26.7406436+07:00 0HLCUJBMNRG9R:00000002 [INF] Executing action method "OneTravelApi.Controllers.CategoryBookingStatusController.GetAll (OneTravelApi)" with arguments (["10", "1", ""]) - ModelState is Valid (ba7f4ac2)
2018-04-10T11:24:26.9048560+07:00 0HLCUJBMNRG9R:00000002 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2018-04-10T11:24:26.9141393+07:00 0HLCUJBMNRG9R:00000002 [INF] Executed action "OneTravelApi.Controllers.CategoryBookingStatusController.GetAll (OneTravelApi)" in 174.68ms (afa2e885)
2018-04-10T11:24:26.9143834+07:00 0HLCUJBMNRG9R:00000002 [INF] Request finished in 181.0555ms 200 application/json; charset=utf-8 (791a596a)
2018-04-10T11:25:09.0036737+07:00 0HLCUJBMNRG9R:00000003 [INF] Request starting HTTP/1.1 PUT http://localhost:52568/api/CategoryBookingStatus/2 application/json-patch+json 124 (ca22a1cb)
2018-04-10T11:25:09.0109096+07:00 0HLCUJBMNRG9R:00000003 [INF] Executing action method "OneTravelApi.Controllers.CategoryBookingStatusController.Update (OneTravelApi)" with arguments (["2", "OneTravelApi.EntityLayer.CategoryBookingStatus"]) - ModelState is Valid (ba7f4ac2)
2018-04-10T11:25:09.0885904+07:00 0HLCUJBMNRG9R:00000003 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2018-04-10T11:25:09.0888604+07:00 0HLCUJBMNRG9R:00000003 [INF] Executed action "OneTravelApi.Controllers.CategoryBookingStatusController.Update (OneTravelApi)" in 79.1863ms (afa2e885)
2018-04-10T11:25:09.0891429+07:00 0HLCUJBMNRG9R:00000003 [INF] Request finished in 85.5748ms 200 application/json; charset=utf-8 (791a596a)
2018-04-10T11:25:23.7508212+07:00 0HLCUJBMNRG9R:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/CategoryBookingStatus   (ca22a1cb)
2018-04-10T11:25:23.7515629+07:00 0HLCUJBMNRG9R:00000004 [INF] Executing action method "OneTravelApi.Controllers.CategoryBookingStatusController.GetAll (OneTravelApi)" with arguments (["10", "1", ""]) - ModelState is Valid (ba7f4ac2)
2018-04-10T11:25:23.7541461+07:00 0HLCUJBMNRG9R:00000004 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2018-04-10T11:25:23.7544782+07:00 0HLCUJBMNRG9R:00000004 [INF] Executed action "OneTravelApi.Controllers.CategoryBookingStatusController.GetAll (OneTravelApi)" in 3.059ms (afa2e885)
2018-04-10T11:25:23.7546968+07:00 0HLCUJBMNRG9R:00000004 [INF] Request finished in 3.997ms 200 application/json; charset=utf-8 (791a596a)
2018-04-10T11:35:07.5964209+07:00 0HLCUJHO0LBOL:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/values   (ca22a1cb)
2018-04-10T11:35:07.5964209+07:00 0HLCUJHO0LBOM:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/   (ca22a1cb)
2018-04-10T11:35:07.6617633+07:00 0HLCUJHO0LBOM:00000001 [INF] Request finished in 88.3956ms 200 text/html (791a596a)
2018-04-10T11:35:07.8320996+07:00 0HLCUJHO0LBOL:00000001 [INF] Request finished in 261.3624ms 404  (791a596a)
2018-04-10T11:35:08.6167560+07:00 0HLCUJHO0LBOM:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/v1/swagger.json   (ca22a1cb)
2018-04-10T11:35:08.6738990+07:00 0HLCUJHO0LBOL:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/favicon-32x32.png   (ca22a1cb)
2018-04-10T11:35:08.6786623+07:00 0HLCUJHO0LBOL:00000002 [INF] Sending file. Request path: '"/favicon-32x32.png"'. Physical path: '"N/A"' (27b0a520)
2018-04-10T11:35:08.6836827+07:00 0HLCUJHO0LBOL:00000002 [INF] Request finished in 9.7755ms 200 image/png (791a596a)
2018-04-10T11:35:08.9190851+07:00 0HLCUJHO0LBOM:00000002 [INF] Request finished in 302.3772ms 200 application/json (791a596a)
2018-04-10T11:41:38.6154351+07:00 0HLCUJLCI4Q7M:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/CategoryCity  0 (ca22a1cb)
2018-04-10T11:41:38.7741613+07:00 0HLCUJLCI4Q7M:00000001 [INF] Executed action "OneTravelApi.Controllers.CategoryCityController.GetAll (OneTravelApi)" in 5.1577ms (afa2e885)
2018-04-10T11:41:38.8425864+07:00 0HLCUJLCI4Q7M:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Unable to resolve service for type 'OneTravelApi.Services.ICategoryCityService' while attempting to activate 'OneTravelApi.Controllers.CategoryCityController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-10T11:41:38.9155922+07:00 0HLCUJLCI4Q7M:00000001 [INF] Request finished in 322.2102ms 500 text/html; charset=utf-8 (791a596a)
2018-04-10T11:42:33.8562033+07:00 0HLCUJLSURLH7:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/CategoryCity   (ca22a1cb)
2018-04-10T11:42:34.0811759+07:00 0HLCUJLSURLH7:00000001 [INF] Executed action "OneTravelApi.Controllers.CategoryCityController.GetAll (OneTravelApi)" in 4.9488ms (afa2e885)
2018-04-10T11:42:34.1463283+07:00 0HLCUJLSURLH7:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Unable to resolve service for type 'OneTravelApi.Services.ICategoryCityService' while attempting to activate 'OneTravelApi.Controllers.CategoryCityController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-10T11:42:34.2216310+07:00 0HLCUJLSURLH7:00000001 [INF] Request finished in 396.0117ms 500 text/html; charset=utf-8 (791a596a)
2018-04-10T11:43:31.6417781+07:00 0HLCUJME7GB4O:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/values   (ca22a1cb)
2018-04-10T11:43:31.8069468+07:00 0HLCUJME7GB4O:00000001 [INF] Request finished in 196.6019ms 404  (791a596a)
2018-04-10T11:43:35.4502289+07:00 0HLCUJME7GB4O:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/CategoryCity   (ca22a1cb)
2018-04-10T11:43:35.6165838+07:00 0HLCUJME7GB4O:00000002 [INF] Executing action method "OneTravelApi.Controllers.CategoryCityController.GetAll (OneTravelApi)" with arguments (["10", "1", ""]) - ModelState is Valid (ba7f4ac2)
2018-04-10T11:43:36.1128623+07:00 0HLCUJME7GB4O:00000002 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2018-04-10T11:43:36.1581075+07:00 0HLCUJME7GB4O:00000002 [INF] Executed action "OneTravelApi.Controllers.CategoryCityController.GetAll (OneTravelApi)" in 610.4092ms (afa2e885)
2018-04-10T11:43:36.1599349+07:00 0HLCUJME7GB4O:00000002 [INF] Request finished in 709.7933ms 200 application/json; charset=utf-8 (791a596a)
2018-04-10T11:43:54.4218342+07:00 0HLCUJME7GB4O:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/   (ca22a1cb)
2018-04-10T11:43:54.4291053+07:00 0HLCUJME7GB4O:00000003 [INF] Request finished in 7.2693ms 200 text/html (791a596a)
2018-04-10T11:43:55.0705753+07:00 0HLCUJME7GB4O:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/v1/swagger.json   (ca22a1cb)
2018-04-10T11:43:55.1157816+07:00 0HLCUJME7GB4P:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/swagger/favicon-32x32.png   (ca22a1cb)
2018-04-10T11:43:55.1196056+07:00 0HLCUJME7GB4P:00000001 [INF] Sending file. Request path: '"/favicon-32x32.png"'. Physical path: '"N/A"' (27b0a520)
2018-04-10T11:43:55.1254572+07:00 0HLCUJME7GB4P:00000001 [INF] Request finished in 9.543ms 200 image/png (791a596a)
2018-04-10T11:43:55.3535326+07:00 0HLCUJME7GB4O:00000004 [INF] Request finished in 282.9555ms 200 application/json (791a596a)
2018-04-10T11:44:20.9099923+07:00 0HLCUJME7GB4P:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:52568/api/CategoryCity application/json-patch+json 99 (ca22a1cb)
2018-04-10T11:44:20.9671363+07:00 0HLCUJME7GB4P:00000002 [INF] Executing action method "OneTravelApi.Controllers.CategoryCityController.Create (OneTravelApi)" with arguments (["OneTravelApi.Resources.CategoryResource"]) - ModelState is Valid (ba7f4ac2)
2018-04-10T11:44:21.0887113+07:00 0HLCUJME7GB4P:00000002 [INF] Executed action "OneTravelApi.Controllers.CategoryCityController.Create (OneTravelApi)" in 169.4419ms (afa2e885)
2018-04-10T11:44:21.1334714+07:00 0HLCUJME7GB4P:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.NullReferenceException: Object reference not set to an instance of an object.
   at OneTravelApi.Services.CategoryCityService.<Create>d__6.MoveNext() in D:\dev\projects\OneTravelCMS\OneTravelApi\Services\ICategoryCityService.cs:line 123
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OneTravelApi.Controllers.CategoryCityController.<Create>d__4.MoveNext() in D:\dev\projects\OneTravelCMS\OneTravelApi\Controllers\CategoryCityController.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-10T11:44:21.2050988+07:00 0HLCUJME7GB4P:00000002 [INF] Request finished in 295.0819ms 500 text/html; charset=utf-8 (791a596a)
2018-04-10T11:46:47.7171040+07:00 0HLCUJO8M087R:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/values   (ca22a1cb)
2018-04-10T11:46:47.8169441+07:00 0HLCUJO8M087R:00000001 [INF] Request finished in 119.7106ms 404  (791a596a)
2018-04-10T11:46:52.9666828+07:00 0HLCUJO8M087R:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:52568/api/CategoryCity application/json-patch+json 99 (ca22a1cb)
2018-04-10T11:46:53.2126368+07:00 0HLCUJO8M087R:00000002 [INF] Executing action method "OneTravelApi.Controllers.CategoryCityController.Create (OneTravelApi)" with arguments (["OneTravelApi.Resources.CategoryCityResource"]) - ModelState is Valid (ba7f4ac2)
2018-04-10T11:46:53.8140337+07:00 0HLCUJO8M087R:00000002 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2018-04-10T11:46:53.8430460+07:00 0HLCUJO8M087R:00000002 [INF] Executed action "OneTravelApi.Controllers.CategoryCityController.Create (OneTravelApi)" in 767.2746ms (afa2e885)
2018-04-10T11:46:53.8476772+07:00 0HLCUJO8M087R:00000002 [INF] Request finished in 881.1206ms 200 application/json; charset=utf-8 (791a596a)
2018-04-10T11:47:06.2494822+07:00 0HLCUJO8M087R:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/CategoryBookingStatus   (ca22a1cb)
2018-04-10T11:47:06.2544699+07:00 0HLCUJO8M087R:00000003 [INF] Executing action method "OneTravelApi.Controllers.CategoryBookingStatusController.GetAll (OneTravelApi)" with arguments (["10", "1", ""]) - ModelState is Valid (ba7f4ac2)
2018-04-10T11:47:06.4353854+07:00 0HLCUJO8M087R:00000003 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2018-04-10T11:47:06.4628913+07:00 0HLCUJO8M087R:00000003 [INF] Executed action "OneTravelApi.Controllers.CategoryBookingStatusController.GetAll (OneTravelApi)" in 209.9907ms (afa2e885)
2018-04-10T11:47:06.4632644+07:00 0HLCUJO8M087R:00000003 [INF] Request finished in 213.7767ms 200 application/json; charset=utf-8 (791a596a)
2018-04-10T11:47:16.8633124+07:00 0HLCUJO8M087R:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:52568/api/CategoryCity   (ca22a1cb)
2018-04-10T11:47:16.8682033+07:00 0HLCUJO8M087R:00000004 [INF] Executing action method "OneTravelApi.Controllers.CategoryCityController.GetAll (OneTravelApi)" with arguments (["10", "1", ""]) - ModelState is Valid (ba7f4ac2)
2018-04-10T11:47:16.8973474+07:00 0HLCUJO8M087R:00000004 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2018-04-10T11:47:16.9059359+07:00 0HLCUJO8M087R:00000004 [INF] Executed action "OneTravelApi.Controllers.CategoryCityController.GetAll (OneTravelApi)" in 37.9712ms (afa2e885)
2018-04-10T11:47:16.9063558+07:00 0HLCUJO8M087R:00000004 [INF] Request finished in 42.9152ms 200 application/json; charset=utf-8 (791a596a)
